### ISSUE TITLE
Add Application Security Definition

### ISSUE THREAD

**Issue by wasciutto** [samoylenko/whatisappsec#10]
It would be nice to start the document with a definition of the "essence" of what it means to be an application security professional. 

Something like...

Application security professionals offer support in the maintenance of code at the application layer in order to minimize the possibility of a security compromise.

**Comment by samoylenko** [comment]
From an unpublished change: "Some of our colleagues say that Application Security is just one of software
development specializations, just like e.g. databases or middleware. Others
think that we are a subset of Testing/Quality Assurance."

**Comment by wasciutto** [comment]
I like and agree with this, but additionally think a description of what the role is attempting to accomplish would be useful.

**Comment by samoylenko** [comment]
Closed in #42

**Comment by samoylenko** [comment]
@wasciutto Hope you'll see this someday, and let me know if this is what you expected :) https://whatisappsec.info/
