### ISSUE TITLE
Add recommendations on prerequisites for appsec projects

### ISSUE THREAD

**Issue by samoylenko** [samoylenko/whatisappsec#5]
Appsec can't be just applied blindly to any project. There are some per-requisites that have to exist before it makes sense e.g. to address vulns.

E.g. application has to have a code repository, dependency management, automatic builds, adequate deployment process

Also some SDLC maturity should be in place

As well as some maturity and integrity on the appsec team side

**Comment by wasciutto** [comment]
Good idea, although this is a point where I would start considering how much detail you want to get into. Perhaps recommending a book on the SDLC would cover this. (I had always considered your first list as part of the SDLC, though I could be wrong)

**Comment by samoylenko** [comment]
This issue is actually the entire reason we've started this project. The idea is to document stuff like 'if you don't have source code management tool, consistent testing and builds embedded in your project, with code reviews etc, it makes no sense for you to jump on security topic, address that first'. As well as 'if you are a security guy, first ensure that you know what you are doing, that you are not only pointing fingers, but are actually helping in a consistent manner. that you are enabling business, and not just a pain in the ass for everybody, trying to police stuff that everybody already knows about'

**Comment by samoylenko** [comment]
The best I could do here is now reflected in https://whatisappsec.info/practices/
